Series 1 blog 4
MAESTRO-Pool/website pull request #17
Opened 2021-07-18 02:37 UTC by MarvinBertin

2021-07-18 17:22 UTC, Vardominator approved these changes
Looks great. Just some grammatical suggestions to help clarify your points.

How about a small blurbs about IOHK and Cardano Foundation and how those things fit into the Cardano ecosystem? We can/should also write about these in future blogs :)

2021-07-18 17:22 UTC, Vardominator commented on content/blog/series_1_blog_4/index.md
> +In recent years, a new wave of cryptocurrencies have entered the market claiming to bring as much fundamental changes to Ethereum as Ethereum brought to Bitcoin, when it introduced smart contracts. T
The first sentence is a bit too long. I recommend: 
`Since 2017, a new wave of cryptocurrencies have brought as many fundamental changes to Ethereum as Ethereum has brought to Bitcoin.`

Would be nice to bold `third generation`:
`These project are coined **Third Generation Cryptocurrencies**` or `**3rd Generation Cryptocurrencies**`

2021-07-18 17:22 UTC, Vardominator commented on content/blog/series_1_blog_4/index.md
> +It is unclear if Bitcoin and Ethereum will maintain their first mover advantage and leave all other projects in the dust. These market leaders benefit from strong network effects thanks to their larg
`They tend to have more novel architectures and superior blockchain designs, however better tech doesn’t always guarantee success.`
=>
`They tend to have more novel architectures and superior blockchain designs. However, better tech doesn’t always guarantee success.`


`In the past, the power of network effects have allowed certain tech companies to monopolize entire market divisions and fend off competition, for example Amazon in e-commerce and Facebook in social networks.`
=>
`In the past, the power of network effects have allowed certain tech companies to monopolize entire market divisions and fend off competition. These companies include Amazon and Facebook with their dominance over e-commerce and social networks, respectively.`

2021-07-18 17:22 UTC, Vardominator commented on content/blog/series_1_blog_4/index.md
> +That being said, the crypto space is still very much in its infancy and as yet to reach global adoption. In comparison, in the 1990s and the early days of the internet, Netscape achieved over 90% mar
`as yet` => `has yet`

`However as we all know, its rein did not last and Netscape eventually lost to Internet Explorer which then lost to Google Chrome.` => `However, its reign over web browsing did not last, and Netscape eventually lost to Internet Explorer, which in turn lost to Google Chrome.`

2021-07-18 17:22 UTC, Vardominator commented on content/blog/series_1_blog_4/index.md
> +This is all to say, third generation cryptos are still very much in the race and have the chops to dethrone any market leaders as the industry matures and adoption grows across the world.
`This is all to say` => `Despite these things`

2021-07-18 17:22 UTC, Vardominator commented on content/blog/series_1_blog_4/index.md
> +Amongst the newcomers, Cardano stands out from the crowd first from its bespoke and cutting edge blockchain architecture. And second, because it has one of the largest and most active community in th
`Amongst the newcomers, Cardano stands out from the crowd first from its bespoke and cutting edge blockchain architecture. And second, because it has one of the largest and most active community in the crypto space.`
=> `Among the newcomers, Cardano stands out from the crowd both from its bespoke and cutting edge blockchain architecture and from its large and active community.`

2021-07-18 17:22 UTC, Vardominator commented on content/blog/series_1_blog_4/index.md
> +Created in 2017 by Charles Hoskinson, a mathematician and blockchain expert, Caradno’s native token ada, almost unknown a year ago, has risen around 6400% since March 2020 and now ranks between the 3
`ada` => `**ADA**` ?

`However` => `However,`

2021-07-18 17:22 UTC, Vardominator commented on content/blog/series_1_blog_4/index.md
> +Created in 2017 by Charles Hoskinson, a mathematician and blockchain expert, Caradno’s native token ada, almost unknown a year ago, has risen around 6400% since March 2020 and now ranks between the 3
Actually super smooth and impactful introduction to Cardano :)

2021-07-18 17:22 UTC, Vardominator commented on content/blog/series_1_blog_4/index.md
> +**Purpose-driven, banking the unbanked** - In contrast to most other projects in the space, Cardano has dedicated its efforts towards global financial inclusion with an emphasis on building out infra
`Purpose-driven, banking the unbanked` = `Purpose-driven; banking the unbanked`

2021-07-18 17:22 UTC, Vardominator commented on content/blog/series_1_blog_4/index.md
> +Recently, it has partnered with the Ethipiopian Ministry of Education to provide a digital national ID system that would enable students to prove their academic credentials to a future employer. In f
`Ethipiopian Ministry of Education` => bold and hyperlink? 

`For example, enabling small businesses to apply for loans or farmers to prove their land ownership.`
=> 
`For example, a decentralized ID can enable small businsses to apply for loans or farmers to prove their land ownership.`

`are holding back` => `is holding back`

`and Cardano fully embodies` => `, and Cardano fully embodies`

2021-07-19 00:16 UTC, ggydush requested changes
Off to a great start! Left a bunch of comments on formatting / typos that MS Word is picking up - were those missed by Google Docs?

2021-07-19 00:16 UTC, ggydush commented on content/blog/series_1_blog_4/index.md
> +The Ouroboros Proof-of-stake consensus algorithm removes the need for power hungry mining infrastructure that is required for Bitcoin’s Proof-of-work protocol.  Running the consensus algorithm and ma
>over XXX stake pools

Don't forget to fill in!

2021-07-19 00:16 UTC, ggydush commented on content/blog/series_1_blog_4/index.md
> +The Ouroboros Proof-of-stake consensus algorithm removes the need for power hungry mining infrastructure that is required for Bitcoin’s Proof-of-work protocol.  Running the consensus algorithm and ma
>mostly owned by individuals and not institutions

can you prove that?

2021-07-19 00:16 UTC, ggydush commented on content/blog/series_1_blog_4/index.md
> +As we saw with Ethereum [link to other part of blog], smart contracts open the door to a lot of exciting new functionality on the blockchain. However decentralized applications can be more complex to
Add link! You can link to a specific section too with `#`

2021-07-19 00:16 UTC, ggydush commented on content/blog/series_1_blog_4/index.md
> +As we saw with Ethereum [link to other part of blog], smart contracts open the door to a lot of exciting new functionality on the blockchain. However decentralized applications can be more complex to
>As we saw with Ethereum [link to other part of blog], smart contracts open the door to a lot of exciting new functionality on the blockchain. However decentralized applications can be more complex to design and implement correctly.

As we saw with Ethereum [link to other part of blog], smart contracts open the door to a lot of exciting new functionality on the blockchain, but decentralized applications can be more complex to design and implement correctly.

2021-07-19 00:16 UTC, ggydush commented on content/blog/series_1_blog_4/index.md
> +As we saw with Ethereum [link to other part of blog], smart contracts open the door to a lot of exciting new functionality on the blockchain. However decentralized applications can be more complex to
To prevent this from happening , <- remove space before comma

2021-07-19 00:16 UTC, ggydush commented on content/blog/series_1_blog_4/index.md
> +As we saw with Ethereum [link to other part of blog], smart contracts open the door to a lot of exciting new functionality on the blockchain. However decentralized applications can be more complex to
> Smart contract’s integrity can now be formally verified before they are deployed

Cardano's smart contract's integrity is formally verified automatically before they are deployed.

2021-07-19 00:16 UTC, ggydush commented on content/blog/series_1_blog_4/index.md
> +In a previous section, we learned about DAOs and how they depart from traditional organizations by getting rid of centralized leadership in favor of a democractic voting system. These new decentraliz
Remove spaces before citations everywhere please!

2021-07-19 00:16 UTC, ggydush commented on content/blog/series_1_blog_4/index.md
> +In a previous section, we learned about DAOs and how they depart from traditional organizations by getting rid of centralized leadership in favor of a democractic voting system. These new decentraliz
> e model in the world. A model

e model in the world - a model

2021-07-19 00:16 UTC, ggydush commented on content/blog/series_1_blog_4/index.md
> +As we saw with Ethereum [link to other part of blog], smart contracts open the door to a lot of exciting new functionality on the blockchain. However decentralized applications can be more complex to
builtin --> built-in

2021-07-19 00:16 UTC, ggydush commented on content/blog/series_1_blog_4/index.md
> +In a previous section, we learned about DAOs and how they depart from traditional organizations by getting rid of centralized leadership in favor of a democractic voting system. These new decentraliz
democractic -> democratic

2021-07-19 00:16 UTC, ggydush commented on content/blog/series_1_blog_4/index.md
> +In a previous section, we learned about DAOs and how they depart from traditional organizations by getting rid of centralized leadership in favor of a democractic voting system. These new decentraliz
well defined --> well-defined

2021-07-19 00:16 UTC, ggydush commented on content/blog/series_1_blog_4/index.md
> +In a previous section, we learned about DAOs and how they depart from traditional organizations by getting rid of centralized leadership in favor of a democractic voting system. These new decentraliz
hardfork --> hard fork isn't it?

2021-07-19 00:16 UTC, ggydush commented on content/blog/series_1_blog_4/index.md
> +Come join us in this crypto journey as we dive deeper into this exciting new technology that is the blockchain. We will learn to navigate the misconceptions and misinformation surrounding the space a
real world --> real-world

2021-07-19 00:16 UTC, ggydush commented on content/blog/series_1_blog_4/index.md
> +Come join us in this crypto journey as we dive deeper into this exciting new technology that is the blockchain. We will learn to navigate the misconceptions and misinformation surrounding the space a
remove "may I dare say"

2021-07-19 00:16 UTC, ggydush commented on content/blog/series_1_blog_4/index.md
> +Come join us in this crypto journey as we dive deeper into this exciting new technology that is the blockchain. We will learn to navigate the misconceptions and misinformation surrounding the space a
In the blockchain code is law -> In the blockchain, code is law

Powerful last words!!

2021-07-20 05:12 UTC, MarvinBertin commented on content/blog/series_1_blog_4/index.md
> +In recent years, a new wave of cryptocurrencies have entered the market claiming to bring as much fundamental changes to Ethereum as Ethereum brought to Bitcoin, when it introduced smart contracts. T
i.e. means "more specifically", whereas e.g. means "for example". Not quite the same thing

2021-07-20 05:14 UTC, MarvinBertin commented on content/blog/series_1_blog_4/index.md
>  > #### Series 1: Cardano The Only True 3rd Generation Crypto
shouldn't titles be capitalized?

2021-07-20 15:12 UTC, ggydush commented on content/blog/series_1_blog_4/index.md
> +In recent years, a new wave of cryptocurrencies have entered the market claiming to bring as much fundamental changes to Ethereum as Ethereum brought to Bitcoin, when it introduced smart contracts. T
We can keep both if you want! I see people usually pick a side and use them interchangeably (both to elaborate / give an example), but maybe that's incorrect usage.

When we use, let's just make sure to use comma and dots on both (e.g., or i.e.,)

2021-07-21 01:21 UTC, merged