Yoroi Microblog
MAESTRO-Pool/website pull request #33
Opened 2021-09-21 05:17 UTC by anoojpatel

2021-09-22 01:24 UTC, Vardominator commented on content/blog/micro_blog_1/index.md
> +A Crypto wallet is a storage mechanism that holds your private keys to keep you tokens safe and accessible. They also have the functionalities of sending, receiving,and in the case of Cardano staking
They also have... => It also has...

2021-09-22 01:29 UTC, Vardominator requested changes

2021-09-22 01:29 UTC, Vardominator commented on content/blog/micro_blog_1/index.md
> +A Crypto wallet is a storage mechanism that holds your private keys to keep you tokens safe and accessible. They also have the functionalities of sending, receiving,and in the case of Cardano staking
They also have... => It also has...

2021-09-22 01:29 UTC, Vardominator commented on content/blog/micro_blog_1/index.md
> +Yoroi is a wallet built by Emrugo, a separate company from IOHK (The group that developed Cardano initially). Yoroi is a very light weight wallet. Yoroi is the most popular wallet for Cardano. It is
`Yoroi is a wallet built by Emrugo, a separate company from IOHK (The group that developed Cardano initially).`

It's probably more accurate to say that they are directly partnered with IOHK rather than a separate company. In fact, they branched out from the same initial group.

2021-09-22 01:29 UTC, Vardominator commented on content/blog/micro_blog_1/index.md
> +Security is a very important component, so it’s important to note that Yoroi is known to be secured. Cardano is designed such that nodes can process individual transactions without relying on storing
Security is a very important component, so it’s important to note that Yoroi is known to be secured. Cardano is designed such that nodes can process individual transactions without relying on storing any private information. This means, you don’t give your private keys to Yoroi!
=> Given that security is a critical component of digital wallets, Yoroi has been designed to processed individual transactions...

2021-09-22 01:29 UTC, Vardominator commented on content/blog/micro_blog_1/index.md
> +* A Cardano wallet on [Daedulus](https://daedaluswallet.io/)
No need to mention Daedalus here at all.

2021-09-22 01:29 UTC, Vardominator commented on content/blog/micro_blog_1/index.md
> +### Using a Daedalus Wallet
I would recommend dedicating a separate micro blog to Daedalus and excluding mention of it here other than maybe a short blurb at the end.

2021-09-25 17:52 UTC, ggydush requested changes

2021-09-25 17:52 UTC, ggydush commented on content/blog/micro_blog_1/index.md
> +date: 2021-09-21
Make sure to update date before merge!

2021-09-25 17:52 UTC, ggydush commented on content/blog/micro_blog_1/index.md
> +A Crypto wallet is a storage mechanism that holds your private keys to keep you tokens safe and accessible. They also have the functionalities of sending, receiving,and in the case of Cardano staking
>to keep you tokens

to keep **your** tokens

2021-09-25 17:52 UTC, ggydush commented on content/blog/micro_blog_1/index.md
> +A Crypto wallet is a storage mechanism that holds your private keys to keep you tokens safe and accessible. They also have the functionalities of sending, receiving,and in the case of Cardano staking
Need a space after the comma after receiving

2021-09-25 17:52 UTC, ggydush commented on content/blog/micro_blog_1/index.md
> +Yoroi is a wallet built by Emrugo, a separate company from IOHK (The group that developed Cardano initially). Yoroi is a very light weight wallet. Yoroi is the most popular wallet for Cardano. It is
`Emrugo` <- make sure to spell this right!

2021-09-25 17:52 UTC, ggydush commented on content/blog/micro_blog_1/index.md
> +Yoroi is a wallet built by Emrugo, a separate company from IOHK (The group that developed Cardano initially). Yoroi is a very light weight wallet. Yoroi is the most popular wallet for Cardano. It is
`browser based` --> `browser-based`

2021-09-25 17:52 UTC, ggydush commented on content/blog/micro_blog_1/index.md
> +A Crypto wallet is a storage mechanism that holds your private keys to keep you tokens safe and accessible. They also have the functionalities of sending, receiving,and in the case of Cardano staking
Crypto doesn't need to be capitalized

2021-09-25 17:52 UTC, ggydush commented on content/blog/micro_blog_1/index.md
> +Yoroi is a wallet built by Emrugo, a separate company from IOHK (The group that developed Cardano initially). Yoroi is a very light weight wallet. Yoroi is the most popular wallet for Cardano. It is
Can we make sure to capitalize all instances of Yoroi, Cardano, Daedalus for consistency

2021-09-25 17:52 UTC, ggydush commented on content/blog/micro_blog_1/index.md
> +A Crypto wallet is a storage mechanism that holds your private keys to keep you tokens safe and accessible. They also have the functionalities of sending, receiving,and in the case of Cardano staking
`They also have... => It also has...`

"It" is fine here, or just say "Wallets"

"and in the case of Cardano staking" -> "and in the case of Cardano, staking"

2021-09-25 17:52 UTC, ggydush commented on content/blog/micro_blog_1/index.md
> +Yoroi is a wallet built by Emrugo, a separate company from IOHK (The group that developed Cardano initially). Yoroi is a very light weight wallet. Yoroi is the most popular wallet for Cardano. It is
lightweight instead of "light weight"

2021-09-25 17:52 UTC, ggydush commented on content/blog/micro_blog_1/index.md
> +Yoroi is a wallet built by Emrugo, a separate company from IOHK (The group that developed Cardano initially). Yoroi is a very light weight wallet. Yoroi is the most popular wallet for Cardano. It is
>Yoroi is the most popular wallet for Cardano

How do we know that?

2021-09-25 17:52 UTC, ggydush commented on content/blog/micro_blog_1/index.md
> +* A Cardano wallet on [Daedulus](https://daedaluswallet.io/)
Oprah makes websites now? Did you mean Opera?

2021-09-25 17:52 UTC, ggydush commented on content/blog/micro_blog_1/index.md
> +* A Cardano wallet on [Daedulus](https://daedaluswallet.io/)
>or any other browser which supports extensions and dynamic JavaScript

I feel like you can remove this

2021-09-25 17:52 UTC, ggydush commented on content/blog/micro_blog_1/index.md
> +1. Navigate [Yoroi’s website](https://yoroi-wallet.com/#/), created by Emurgo.
**Navigate to

2021-09-25 17:52 UTC, ggydush commented on content/blog/micro_blog_1/index.md
> +2. Click the download button and select the Browser type you’re looking to install! Note you can also install this on iOS and Android as well, because this is also a mobile wallet.
>, because this is also a mobile wallet.

Extraneous

2021-09-25 17:52 UTC, ggydush commented on content/blog/micro_blog_1/index.md
> +3. Once you click download, you’ll be navigated to the browser’s respective extension/app store. Select download, and you will be returned back to the yoroi-wallet.com. Note, you can confirm that the
"you'll" is used first, then "you will" <- pick a side

2021-09-25 17:52 UTC, ggydush commented on content/blog/micro_blog_1/index.md
> +3. Once you click download, you’ll be navigated to the browser’s respective extension/app store. Select download, and you will be returned back to the yoroi-wallet.com. Note, you can confirm that the
Make these links? yoroi-wallet.com

2021-09-25 17:52 UTC, ggydush commented on content/blog/micro_blog_1/index.md
> +3. Once you click download, you’ll be navigated to the browser’s respective extension/app store. Select download, and you will be returned back to the yoroi-wallet.com. Note, you can confirm that the
>Note, you can confirm that the developer is correct, by inspecting the Offered by: to be yoroiwallet.com.

They just came from yoroi-wallet.com, I feel like this is also extraneous info

2021-09-25 17:52 UTC, ggydush commented on content/blog/micro_blog_1/index.md
> +---
Can you work on adding some spacing in places? A lot of this has no spacing between steps and it makes it look a little cluttered

2021-09-25 17:52 UTC, ggydush commented on content/blog/micro_blog_1/index.md
> +---
At least a line break between each of the steps! We may want to consider adding some margin to all the images with CSS

2021-09-25 17:52 UTC, ggydush commented on content/blog/micro_blog_1/index.md
> +---
Maybe also put the text before the image? It's a little confusing to have it the other way around.

2021-09-25 17:52 UTC, ggydush commented on content/blog/micro_blog_1/index.md
> +6. A notification to enable cardano URLs and links will appear. This is for making transactions with other cardano webapps easier and allow extensions to utilize the wallet on different websites, sim
capitalize Cardano - make sure to go through and check all instances!

2021-09-25 17:52 UTC, ggydush commented on content/blog/micro_blog_1/index.md
> +![Notification Insructions](yoroi_payments_notif_page.png) If you’re interested, make sure to continue and hit Allow for your browser.
This is just floating text right now. Maybe remove the image and put the text in step 6?

2021-09-25 17:52 UTC, ggydush commented on content/blog/micro_blog_1/index.md
> +3. You’ll see a display similar to this, where you can give your wallet and a password for spending. Password for spending means you will have to type this password in everytime you want to spend. No
"where you can give your wallet"  "where you can give your wallet a name"

2021-09-25 17:52 UTC, ggydush commented on content/blog/micro_blog_1/index.md
> +3. You’ll see a display similar to this, where you can give your wallet and a password for spending. Password for spending means you will have to type this password in everytime you want to spend. No
Maybe something like this? Spending passwords are a little confusing at first, let's make them less confusing!

For most interactions with your wallet, you will need to use your spending password for security reasons. The spending password is unique to this computer / installation of Yoroi, and if you ever recover your wallet on another computer, you will choose a new spending password.

2021-09-25 17:52 UTC, ggydush commented on content/blog/micro_blog_1/index.md
> +5. **IMPORTANT!** Save these phrases and order of the phrases down to a place that isn’t digital like a paper notebook  (If your cloud accounts are hacked and get to your recovery phrases, they can g
>Save these phrases and order of the phrases down to a place that isn’t digital like a paper notebook 

Consider revising. This is the most important step, so we want to be sure the users know what they are doing.

These phrases are the key to unlock all of your funds. Make sure to be extremely careful with storing them. We recommend getting out a piece of paper, writing down the seed phrase, checking it twice, and storing with your other sensitive documents. We highly recommend against storing them online, but if you must, consider creating a poem or short story using the words in the seed phrase so that you are the only one who can decipher it.

2021-09-25 17:52 UTC, ggydush commented on content/blog/micro_blog_1/index.md
> +8. Look up a stake pool to delegate to (in our case, MAESTRO Pool), and select delegate. Here you can select an amount ADA that you want to delegate to this specific pool! **Note** that you will have
Maybe link to the FAQ here as well? More information can be found on our FAQ <- link to the FAQ

2021-09-25 17:52 UTC, ggydush commented on content/blog/micro_blog_1/index.md
> +### Using a Daedalus Wallet
+1

2021-09-25 17:52 UTC, ggydush commented on content/blog/micro_blog_1/index.md
> +### Using a Daedalus Wallet
Or at least rename this section to "Using a previously created Daedalus Wallet with Yoroi"

2021-09-25 17:52 UTC, ggydush commented on content/blog/micro_blog_1/index.md
> +3. The wallet will not let you recover if the phrase is not correct, and until the “continue” button turns, green, it won’t complete
We didn't mention anything about the checksum above... should we add a blurb on it?

2021-09-25 17:52 UTC, ggydush commented on content/blog/micro_blog_1/index.md
> +---
Could we also try to have all of the images be the same size? If you have your browser in full screen, and take an image for each step, the images should all be the same size!

2021-09-25 19:59 UTC, anoojpatel commented on content/blog/micro_blog_1/index.md
> +Yoroi is a wallet built by Emrugo, a separate company from IOHK (The group that developed Cardano initially). Yoroi is a very light weight wallet. Yoroi is the most popular wallet for Cardano. It is
Just assumed from google trends, and downloads from chrome extensions/google play https://trends.google.com/trends/explore?geo=US&q=daedalus%20wallet,yoroi%20wallet. I can change to "a popular" to avoid making claims

2021-09-28 17:37 UTC, anoojpatel commented on content/blog/micro_blog_1/index.md
> +3. Once you click download, you’ll be navigated to the browser’s respective extension/app store. Select download, and you will be returned back to the yoroi-wallet.com. Note, you can confirm that the
I wanted to add this confirmation bc people have been bamboozled with MitM attacks or XSS attacks that reroute them to a hacked version of the extension.

2021-09-28 17:43 UTC, anoojpatel commented on content/blog/micro_blog_1/index.md
> +3. The wallet will not let you recover if the phrase is not correct, and until the “continue” button turns, green, it won’t complete
I think actually I might remove this step, I can't find any information about wallet restoration checksums from Daedalus. I think an account checksum is only a feature for yoroi, as Daedalus doesn't seem to have one. Heh, kinda strange

2021-09-29 17:09 UTC, ggydush approved these changes

2021-09-29 18:01 UTC, Vardominator requested changes

2021-09-29 18:15 UTC, Vardominator approved these changes

2021-09-29 18:16 UTC, merged